# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96146e1fd1469dc47264c65933111717059534d8eb0811f3ea1f14a72078b874f6713bc5fc795d62066308c6fe516d1f02d32cc2226499525cfa2af2a46d3d50

test:
  secret_key_base: d06ae46affba9f0a5f884385201d21a3f61617436b160ffc4c065df9851f3a310dffe44018dd55f9e07c96c3ad295bc4466d8ec8968c1d21361754a059654e0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
